name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7

      - name: Make binaries
        uses: Nitecon/actions/golang@main
        env:
          APP_NAME: "HostX"

      - name: Create release with GitReleaseManager
        uses: gittools/actions/gitreleasemanager/create@v0.9.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: $GITHUB_REPOSITORY_OWNER
          repository: hostx
          milestone: $GITVERSION_SEMVER
          name: "v${GITVERSION_SEMVER}"
          assets: |
            ${GITHUB_WORKSPACE}/.build/HostX.zip

      #- name: Test
      #  run: go test -v ./...
