name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Setup semantic-release
        run: npm install -g semantic-release

      - name: Get semantic release version
        run: npx -p @semantic-release/exec -p semantic-release semantic-release --dry-run --plugins "@semantic-release/commit-analyzer,@semantic-release/exec" --analyzeCommits @semantic-release/commit-analyzer --verifyRelease @semantic-release/exec --verifyReleaseCmd "echo ${nextRelease.version} > APP_VERSION.txt"

      #- name: Release
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  run: semantic-release --dry-run --no-ci --branches main

      - name: List workspace
        run: ls -alh

      - name: store envar
        run: echo "APP_SEMVER=$(cat APP_VERSION.txt)" >> $GITHUB_ENV

      - name: Make binaries
        uses: Nitecon/actions/golang@main
        env:
          APP_NAME: "HostX"

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release --no-ci --branches main



      #- name: Test
      #  run: go test -v ./...
