---
apiVersion: v1
kind: Namespace
metadata:
  name: hostx
---
apiVersion: v1
data:
  AWS_KEY: a2V5Cg==
  AWS_SECRET: c2VjcmV0Cg==
  BUCKET: dGhlYnVja2V0Cg==
kind: Secret
metadata:
  name: hostx-config
  namespace: hostx
type: Opaque